create table if not exists public.tamanos (
  id bigint generated by default as identity primary key,
  nombre text not null,
  modalidad text not null,
  precio_menudeo numeric not null default 0,
  precio_mayoreo numeric not null default 0,
  created_at timestamptz not null default now()
);

alter table public.productos
  add column if not exists tamanos jsonb not null default '[]'::jsonb;

create index if not exists tamanos_nombre_modalidad_idx
  on public.tamanos (nombre, modalidad);

select pg_notify('pgrst', 'reload schema');
