create table if not exists public.tamanos (
  id bigint generated by default as identity primary key,
  nombre text not null,
  modalidad text not null,
  precio_menudeo numeric not null default 0,
  precio_mayoreo numeric not null default 0,
  created_at timestamptz not null default now()
);

alter table public.productos
  add column if not exists tamanos jsonb not null default '[]'::jsonb;

create index if not exists tamanos_nombre_modalidad_idx
  on public.tamanos (nombre, modalidad);

alter table public.tamanos enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'tamanos'
      and policyname = 'tamanos_public_select'
  ) then
    create policy tamanos_public_select
      on public.tamanos
      for select
      to anon, authenticated
      using (true);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'tamanos'
      and policyname = 'tamanos_public_insert'
  ) then
    create policy tamanos_public_insert
      on public.tamanos
      for insert
      to anon, authenticated
      with check (true);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'tamanos'
      and policyname = 'tamanos_public_update'
  ) then
    create policy tamanos_public_update
      on public.tamanos
      for update
      to anon, authenticated
      using (true)
      with check (true);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'tamanos'
      and policyname = 'tamanos_public_delete'
  ) then
    create policy tamanos_public_delete
      on public.tamanos
      for delete
      to anon, authenticated
      using (true);
  end if;
end $$;

select pg_notify('pgrst', 'reload schema');
