import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body>
  <nav className="bg-black text-white p-4 flex gap-6">
    <a href="/" className="font-bold">Inicio</a>
    <a href="/catalogo">Catálogo</a>
    <a href="/pedido">Pedido</a>
    <a href="/admin">Admin</a>
  </nav>

  <main>
    {children}
  </main>
</body>
    </html>
  );
}
